/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dipu;

import java.awt.Color;

/**
 *
 * @author DIPU
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public AdminDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        panelsearch = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        butttonsearch = new javax.swing.JLabel();
        paneledit = new javax.swing.JPanel();
        buttonedit = new javax.swing.JLabel();
        panelview = new javax.swing.JPanel();
        buttonviewpayment = new javax.swing.JLabel();
        panellogout = new javax.swing.JPanel();
        buttonlogout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 80, 80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADMIN DASHBOARD");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 510, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 100));

        jPanel2.setBackground(new java.awt.Color(0, 140, 140));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelsearch.setBackground(new java.awt.Color(0, 80, 80));
        panelsearch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.black, null));
        panelsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelsearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelsearchMouseExited(evt);
            }
        });
        panelsearch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Search Record");
        jLabel7.setToolTipText("");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelsearch.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 170, 50));

        butttonsearch.setBackground(new java.awt.Color(255, 255, 255));
        butttonsearch.setFont(new java.awt.Font("Arial", 0, 27)); // NOI18N
        butttonsearch.setForeground(new java.awt.Color(255, 255, 255));
        butttonsearch.setIcon(new javax.swing.ImageIcon("C:\\Users\\DIPU\\Desktop\\JU_Fees_Management\\src\\main\\java\\dipu\\Icons\\search-document.png")); // NOI18N
        butttonsearch.setToolTipText("");
        butttonsearch.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        butttonsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butttonsearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butttonsearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butttonsearchMouseExited(evt);
            }
        });
        panelsearch.add(butttonsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 330, 230));

        jPanel2.add(panelsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 360, 250));

        paneledit.setBackground(new java.awt.Color(0, 80, 80));
        paneledit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.black, null));
        paneledit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paneleditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paneleditMouseExited(evt);
            }
        });
        paneledit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonedit.setBackground(new java.awt.Color(255, 255, 255));
        buttonedit.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        buttonedit.setForeground(new java.awt.Color(255, 255, 255));
        buttonedit.setIcon(new javax.swing.ImageIcon("C:\\Users\\DIPU\\Desktop\\JU_Fees_Management\\src\\main\\java\\dipu\\Icons\\edit.png")); // NOI18N
        buttonedit.setText("Student Information");
        buttonedit.setToolTipText("");
        buttonedit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonedit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttoneditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttoneditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttoneditMouseExited(evt);
            }
        });
        paneledit.add(buttonedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 340, 220));

        jPanel2.add(paneledit, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 360, 250));

        panelview.setBackground(new java.awt.Color(0, 80, 80));
        panelview.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.black, null));
        panelview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelviewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelviewMouseExited(evt);
            }
        });
        panelview.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonviewpayment.setBackground(new java.awt.Color(255, 255, 255));
        buttonviewpayment.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        buttonviewpayment.setForeground(new java.awt.Color(255, 255, 255));
        buttonviewpayment.setIcon(new javax.swing.ImageIcon("C:\\Users\\DIPU\\Desktop\\JU_Fees_Management\\src\\main\\java\\dipu\\Icons\\text-book-opened-from-top-view.png")); // NOI18N
        buttonviewpayment.setText("View Payment");
        buttonviewpayment.setToolTipText("");
        buttonviewpayment.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonviewpayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonviewpaymentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonviewpaymentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonviewpaymentMouseExited(evt);
            }
        });
        panelview.add(buttonviewpayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 340, 220));

        jPanel2.add(panelview, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 360, 250));

        panellogout.setBackground(new java.awt.Color(0, 80, 80));
        panellogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.black, null));
        panellogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panellogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panellogoutMouseExited(evt);
            }
        });
        panellogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonlogout.setBackground(new java.awt.Color(255, 255, 255));
        buttonlogout.setFont(new java.awt.Font("Arial", 0, 27)); // NOI18N
        buttonlogout.setForeground(new java.awt.Color(255, 255, 255));
        buttonlogout.setIcon(new javax.swing.ImageIcon("C:\\Users\\DIPU\\Desktop\\JU_Fees_Management\\src\\main\\java\\dipu\\Icons\\logout_1.png")); // NOI18N
        buttonlogout.setText(" Logout ");
        buttonlogout.setToolTipText("");
        buttonlogout.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonlogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonlogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonlogoutMouseExited(evt);
            }
        });
        panellogout.add(buttonlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 340, 220));

        jPanel2.add(panellogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, 360, 250));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1070, 770));

        setSize(new java.awt.Dimension(1085, 811));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void panelsearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelsearchMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelsearchMouseEntered

    private void panelsearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelsearchMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panelsearchMouseExited

    private void paneleditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneleditMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_paneleditMouseEntered

    private void paneleditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneleditMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_paneleditMouseExited

    private void panelviewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelviewMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelviewMouseEntered

    private void panelviewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelviewMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panelviewMouseExited

    private void panellogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panellogoutMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panellogoutMouseEntered

    private void panellogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panellogoutMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panellogoutMouseExited

    private void butttonsearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butttonsearchMouseEntered
        Color clr = new Color(0,50,50);
        panelsearch.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_butttonsearchMouseEntered

    private void butttonsearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butttonsearchMouseExited
        Color clr = new Color(0, 100, 100);
        panelsearch.setBackground(clr); // TODO add your handling code here:
    }//GEN-LAST:event_butttonsearchMouseExited

    private void buttoneditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttoneditMouseEntered
        Color clr = new Color(0,50,50);
        paneledit.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_buttoneditMouseEntered

    private void buttoneditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttoneditMouseExited
         Color clr = new Color(0, 100, 100);
        paneledit.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_buttoneditMouseExited

    private void buttonviewpaymentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonviewpaymentMouseEntered
       Color clr = new Color(0,50,50);
        panelview.setBackground(clr); // TODO add your handling code here:
    }//GEN-LAST:event_buttonviewpaymentMouseEntered

    private void buttonviewpaymentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonviewpaymentMouseExited
         Color clr = new Color(0, 100, 100);
        panelview.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_buttonviewpaymentMouseExited

    private void buttonlogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonlogoutMouseEntered
        Color clr = new Color(0,50,50);
        panellogout.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_buttonlogoutMouseEntered

    private void buttonlogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonlogoutMouseExited
        Color clr = new Color(0, 100, 100);
        panellogout.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_buttonlogoutMouseExited

    private void buttoneditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttoneditMouseClicked
         dispose();
        Studentinfo v=new Studentinfo();
        v.setVisible(true);
             // TODO add your handling code here:
    }//GEN-LAST:event_buttoneditMouseClicked

    private void butttonsearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butttonsearchMouseClicked
        dispose();
        Search h=new Search();
        h.setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_butttonsearchMouseClicked

    private void buttonviewpaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonviewpaymentMouseClicked
                  dispose();
        Viewstudentpayment h=new Viewstudentpayment();
        h.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_buttonviewpaymentMouseClicked

    private void buttonlogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonlogoutMouseClicked
        dispose();
        Homepage h=new Homepage();
        h.setVisible(true);
             // TODO add your handling code here:
    }//GEN-LAST:event_buttonlogoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buttonedit;
    private javax.swing.JLabel buttonlogout;
    private javax.swing.JLabel buttonviewpayment;
    private javax.swing.JLabel butttonsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel paneledit;
    private javax.swing.JPanel panellogout;
    private javax.swing.JPanel panelsearch;
    private javax.swing.JPanel panelview;
    // End of variables declaration//GEN-END:variables
}
