/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dipu;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author DIPU
 */
public class Payment extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    
    public Payment() {
        initComponents();
        displaycardfirst();
    }
    public void displaycardfirst(){
        cheque.setVisible(false);
        chequebox.setVisible(false);
        //card.setVisible(false);
        //cardbox.setVisible(false);
        phone.setVisible(false);
        txt_phone.setVisible(false);
        //  cvv.setVisible(false);
        //cvvbox.setVisible(false);
         bank.setVisible(false);
         Bankbox.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelsidebar = new javax.swing.JPanel();
        panelhome = new javax.swing.JPanel();
        buttonhome = new javax.swing.JLabel();
        paneledit = new javax.swing.JPanel();
        buttonedit = new javax.swing.JLabel();
        panelrecord = new javax.swing.JPanel();
        buttonrecord = new javax.swing.JLabel();
        panelback = new javax.swing.JPanel();
        buttonback = new javax.swing.JLabel();
        panellogout = new javax.swing.JPanel();
        buttonlogout = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        datecombo = new com.toedter.calendar.JDateChooser();
        phone = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        paymentcombo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        bank = new javax.swing.JLabel();
        Bankbox = new javax.swing.JTextField();
        chequebox = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        txt_amount = new javax.swing.JTextField();
        card = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_course = new javax.swing.JTextField();
        txt_roll = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        remarksbox = new javax.swing.JTextArea();
        txt_submit = new javax.swing.JButton();
        cardbox = new javax.swing.JTextField();
        txt_phone = new javax.swing.JTextField();
        cvvbox = new javax.swing.JTextField();
        cheque = new javax.swing.JLabel();
        cvv = new javax.swing.JLabel();
        txt_session = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelsidebar.setBackground(new java.awt.Color(0, 80, 80));
        panelsidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelhome.setBackground(new java.awt.Color(0, 140, 140));
        panelhome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelhome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonhome.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        buttonhome.setForeground(new java.awt.Color(255, 255, 255));
        buttonhome.setIcon(new javax.swing.ImageIcon("C:\\Users\\DIPU\\Desktop\\JU_Fees_Management\\src\\main\\java\\dipu\\Icons\\home.png")); // NOI18N
        buttonhome.setText(" Home");
        buttonhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonhomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonhomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonhomeMouseExited(evt);
            }
        });
        panelhome.add(buttonhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 360, 70));

        panelsidebar.add(panelhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 390, 70));

        paneledit.setBackground(new java.awt.Color(0, 140, 140));
        paneledit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        paneledit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonedit.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        buttonedit.setForeground(new java.awt.Color(255, 255, 255));
        buttonedit.setIcon(new javax.swing.ImageIcon("C:\\Users\\DIPU\\Desktop\\JU_Fees_Management\\src\\main\\java\\dipu\\Icons\\edit2.png")); // NOI18N
        buttonedit.setText(" Edit Course");
        buttonedit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttoneditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttoneditMouseExited(evt);
            }
        });
        paneledit.add(buttonedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 360, 70));

        panelsidebar.add(paneledit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 390, 70));

        panelrecord.setBackground(new java.awt.Color(0, 140, 140));
        panelrecord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelrecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonrecord.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        buttonrecord.setForeground(new java.awt.Color(255, 255, 255));
        buttonrecord.setIcon(new javax.swing.ImageIcon("C:\\Users\\DIPU\\Desktop\\JU_Fees_Management\\src\\main\\java\\dipu\\Icons\\view all record.png")); // NOI18N
        buttonrecord.setText(" View All Record");
        buttonrecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonrecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonrecordMouseExited(evt);
            }
        });
        panelrecord.add(buttonrecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 380, 70));

        panelsidebar.add(panelrecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 390, 70));

        panelback.setBackground(new java.awt.Color(0, 140, 140));
        panelback.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panelback.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonback.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        buttonback.setForeground(new java.awt.Color(255, 255, 255));
        buttonback.setIcon(new javax.swing.ImageIcon("C:\\Users\\DIPU\\Desktop\\JU_Fees_Management\\src\\main\\java\\dipu\\Icons\\left-arrow.png")); // NOI18N
        buttonback.setText("Back");
        buttonback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonbackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonbackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonbackMouseExited(evt);
            }
        });
        panelback.add(buttonback, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 370, 70));

        panelsidebar.add(panelback, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 390, 70));

        panellogout.setBackground(new java.awt.Color(0, 140, 140));
        panellogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        panellogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonlogout.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        buttonlogout.setForeground(new java.awt.Color(255, 255, 255));
        buttonlogout.setIcon(new javax.swing.ImageIcon("C:\\Users\\DIPU\\Desktop\\JU_Fees_Management\\src\\main\\java\\dipu\\Icons\\logout.png")); // NOI18N
        buttonlogout.setText(" Logout");
        buttonlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonlogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonlogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonlogoutMouseExited(evt);
            }
        });
        panellogout.add(buttonlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 370, 70));

        panelsidebar.add(panellogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 390, 70));

        getContentPane().add(panelsidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 830));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Date : ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 50, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Name : ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Remarks : ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Payment Mode : ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Session : ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        datecombo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(datecombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 160, -1));

        phone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        phone.setForeground(new java.awt.Color(0, 0, 0));
        phone.setText("Phone No : ");
        jPanel1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Roll No : ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        paymentcombo.setBackground(new java.awt.Color(255, 255, 255));
        paymentcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Card", "Bkash", "Nagad", "Cheque" }));
        paymentcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentcomboActionPerformed(evt);
            }
        });
        jPanel1.add(paymentcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 110, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Course : ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        bank.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bank.setForeground(new java.awt.Color(0, 0, 0));
        bank.setText("Bank Name : ");
        jPanel1.add(bank, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 90, -1));

        Bankbox.setBackground(new java.awt.Color(255, 255, 255));
        Bankbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BankboxActionPerformed(evt);
            }
        });
        jPanel1.add(Bankbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 240, -1));

        chequebox.setBackground(new java.awt.Color(255, 255, 255));
        chequebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chequeboxActionPerformed(evt);
            }
        });
        jPanel1.add(chequebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 240, -1));

        txt_name.setBackground(new java.awt.Color(255, 255, 255));
        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 280, -1));

        txt_amount.setBackground(new java.awt.Color(255, 255, 255));
        txt_amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_amountActionPerformed(evt);
            }
        });
        jPanel1.add(txt_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 130, -1));

        card.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        card.setForeground(new java.awt.Color(0, 0, 0));
        card.setText("Card  No : ");
        jPanel1.add(card, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Amount : ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        txt_course.setBackground(new java.awt.Color(255, 255, 255));
        txt_course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_courseActionPerformed(evt);
            }
        });
        jPanel1.add(txt_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 270, -1));

        txt_roll.setBackground(new java.awt.Color(255, 255, 255));
        txt_roll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rollActionPerformed(evt);
            }
        });
        jPanel1.add(txt_roll, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 130, -1));

        remarksbox.setBackground(new java.awt.Color(255, 255, 255));
        remarksbox.setColumns(20);
        remarksbox.setRows(5);
        jScrollPane1.setViewportView(remarksbox);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 440, 80));

        txt_submit.setBackground(new java.awt.Color(0, 80, 80));
        txt_submit.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txt_submit.setText("Submit");
        txt_submit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        txt_submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_submitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_submitMouseExited(evt);
            }
        });
        txt_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_submitActionPerformed(evt);
            }
        });
        jPanel1.add(txt_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 660, 140, 50));

        cardbox.setBackground(new java.awt.Color(255, 255, 255));
        cardbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardboxActionPerformed(evt);
            }
        });
        jPanel1.add(cardbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 240, -1));

        txt_phone.setBackground(new java.awt.Color(255, 255, 255));
        txt_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_phoneActionPerformed(evt);
            }
        });
        jPanel1.add(txt_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 240, -1));

        cvvbox.setBackground(new java.awt.Color(255, 255, 255));
        cvvbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvvboxActionPerformed(evt);
            }
        });
        jPanel1.add(cvvbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 130, -1));

        cheque.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cheque.setForeground(new java.awt.Color(0, 0, 0));
        cheque.setText("Cheque No : ");
        jPanel1.add(cheque, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        cvv.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cvv.setForeground(new java.awt.Color(0, 0, 0));
        cvv.setText("CVV No : ");
        jPanel1.add(cvv, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        txt_session.setBackground(new java.awt.Color(255, 255, 255));
        txt_session.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sessionActionPerformed(evt);
            }
        });
        jPanel1.add(txt_session, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 270, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 810, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonhomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhomeMouseEntered
        Color clr = new Color(0, 100, 100);
        panelhome.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_buttonhomeMouseEntered

    private void buttonhomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhomeMouseExited
        Color clr = new Color(0,140,140);
        panelhome.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_buttonhomeMouseExited

    private void buttoneditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttoneditMouseEntered
       Color clr = new Color(0, 100, 100);
        paneledit.setBackground(clr); // TODO add your handling code here:
    }//GEN-LAST:event_buttoneditMouseEntered

    private void buttoneditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttoneditMouseExited
       Color clr = new Color(0,140,140);
        paneledit.setBackground(clr); // TODO add your handling code here:
    }//GEN-LAST:event_buttoneditMouseExited

    private void buttonhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhomeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonhomeMouseClicked

    private void buttonrecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonrecordMouseEntered
        Color clr = new Color(0, 100, 100);
        panelrecord.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_buttonrecordMouseEntered

    private void buttonrecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonrecordMouseExited
        Color clr = new Color(0,140,140);
        panelrecord.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_buttonrecordMouseExited

    private void buttonbackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonbackMouseEntered
         Color clr = new Color(0, 100, 100);
        panelback.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_buttonbackMouseEntered

    private void buttonbackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonbackMouseExited
        Color clr = new Color(0,140,140);
        panelback.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_buttonbackMouseExited

    private void buttonlogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonlogoutMouseEntered
       Color clr = new Color(0, 100, 100);
        panellogout.setBackground(clr); // TODO add your handling code here:
    }//GEN-LAST:event_buttonlogoutMouseEntered

    private void buttonlogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonlogoutMouseExited
        Color clr = new Color(0,140,140);
        panellogout.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_buttonlogoutMouseExited

    private void BankboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BankboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BankboxActionPerformed

    private void chequeboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chequeboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chequeboxActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void txt_amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_amountActionPerformed
        
        Float amnt = Float.parseFloat(txt_amount.getText());
//       txtamount.setText(Float.toString(amnt));        
//       txt_total.setText(NumberToWordConverter.convert((int)amnt)+" Only");
        
    }//GEN-LAST:event_txt_amountActionPerformed

    private void txt_courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_courseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_courseActionPerformed

    private void txt_rollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rollActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rollActionPerformed

    private void txt_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_submitActionPerformed
      
        Connect connect = new Connect();
        Connection connection = connect.getConnection();
        
        String fname = txt_name.getText();
        String froll = txt_roll.getText();
        String fcourse = txt_course.getText();
        String fphone = txt_phone.getText();
        String fsession = txt_session.getText();
        String famount = txt_amount.getText();
        
        
        
        if(false){

        }
       else{
            
            String q = "INSERT INTO bkash(name, roll, course, phone,session,amount) VALUES (?,?,?,?,?,?)";
        try {
            PreparedStatement ps = connection.prepareStatement(q);
            ps.setString(1, fname);
            ps.setString(2, froll);
            ps.setString(3,fcourse);
             ps.setString(4,fphone);
            ps.setString(5, fsession);
            ps.setString(6, famount);
             ps.executeUpdate();
//            System.out.println(row);
           
            JOptionPane.showMessageDialog(null,"Submitted Succussfully");
        } catch (SQLException ex) {
            Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
        }
        
               }
        
        
    }//GEN-LAST:event_txt_submitActionPerformed

    private void cardboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardboxActionPerformed

    private void txt_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_phoneActionPerformed

    private void cvvboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvvboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cvvboxActionPerformed

    private void paymentcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentcomboActionPerformed
           if((paymentcombo.getSelectedIndex()==1)||(paymentcombo.getSelectedIndex()==2)) {
        cheque.setVisible(false);
        chequebox.setVisible(false);
        card.setVisible(false);
        cardbox.setVisible(false);
        phone.setVisible(true);
        txt_phone.setVisible(true);
        cvv.setVisible(false);
        cvvbox.setVisible(false);
        bank.setVisible(false);
        Bankbox.setVisible(false);
           }
        
        
         if(paymentcombo.getSelectedIndex()==3) {
        cheque.setVisible(true);
        chequebox.setVisible(true);
        card.setVisible(false);
        cardbox.setVisible(false);
        phone.setVisible(false);
        txt_phone.setVisible(false);
        cvv.setVisible(false);
        cvvbox.setVisible(false);
        bank.setVisible(true);
        Bankbox.setVisible(true);
         }
        
        if(paymentcombo.getSelectedIndex()==0) {
        cheque.setVisible(false);
        chequebox.setVisible(false);
        card.setVisible(true);
        cardbox.setVisible(true);
        phone.setVisible(false);
        txt_phone.setVisible(false);
        cvv.setVisible(true);
        cvvbox.setVisible(true);
        bank.setVisible(false);
        Bankbox.setVisible(false);
        
           }        // TODO add your handling code here:
    }//GEN-LAST:event_paymentcomboActionPerformed

    private void txt_sessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sessionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sessionActionPerformed

    private void buttonlogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonlogoutMouseClicked
        dispose();
       Login h=new Login();
        h.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_buttonlogoutMouseClicked

    private void buttonbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonbackMouseClicked
       dispose();
        StudentDashboard h=new StudentDashboard();
        h.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_buttonbackMouseClicked

    private void txt_submitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_submitMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_submitMouseEntered

    private void txt_submitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_submitMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_submitMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        Payment dd = new Payment();
        dd.displaycardfirst();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Payment().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bankbox;
    private javax.swing.JLabel bank;
    private javax.swing.JLabel buttonback;
    private javax.swing.JLabel buttonedit;
    private javax.swing.JLabel buttonhome;
    private javax.swing.JLabel buttonlogout;
    private javax.swing.JLabel buttonrecord;
    private javax.swing.JLabel card;
    private javax.swing.JTextField cardbox;
    private javax.swing.JLabel cheque;
    private javax.swing.JTextField chequebox;
    private javax.swing.JLabel cvv;
    private javax.swing.JTextField cvvbox;
    private com.toedter.calendar.JDateChooser datecombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelback;
    private javax.swing.JPanel paneledit;
    private javax.swing.JPanel panelhome;
    private javax.swing.JPanel panellogout;
    private javax.swing.JPanel panelrecord;
    private javax.swing.JPanel panelsidebar;
    private javax.swing.JComboBox<String> paymentcombo;
    private javax.swing.JLabel phone;
    private javax.swing.JTextArea remarksbox;
    private javax.swing.JTextField txt_amount;
    private javax.swing.JTextField txt_course;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_roll;
    private javax.swing.JTextField txt_session;
    private javax.swing.JButton txt_submit;
    // End of variables declaration//GEN-END:variables
}
