/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dipu;

import java.awt.Color;

/**
 *
 * @author DIPU
 */
public class StudentDashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public StudentDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        panelpayment = new javax.swing.JPanel();
        buttonpayment = new javax.swing.JLabel();
        paneledit = new javax.swing.JPanel();
        buttonedit = new javax.swing.JLabel();
        panelview = new javax.swing.JPanel();
        buttonview = new javax.swing.JLabel();
        panellogout = new javax.swing.JPanel();
        buttonlogout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 80, 80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DASHBOARD");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 320, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 100));

        jPanel2.setBackground(new java.awt.Color(0, 140, 140));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelpayment.setBackground(new java.awt.Color(0, 80, 80));
        panelpayment.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.black, null));
        panelpayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelpaymentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelpaymentMouseExited(evt);
            }
        });
        panelpayment.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonpayment.setBackground(new java.awt.Color(255, 255, 255));
        buttonpayment.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        buttonpayment.setForeground(new java.awt.Color(255, 255, 255));
        buttonpayment.setIcon(new javax.swing.ImageIcon("C:\\Users\\DIPU\\Desktop\\JU_Fees_Management\\src\\main\\java\\dipu\\Icons\\plus2.png")); // NOI18N

        buttonpayment.setText("  Payment");
        buttonpayment.setToolTipText("");
        buttonpayment.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonpayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonpaymentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonpaymentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonpaymentMouseExited(evt);
            }
        });
        panelpayment.add(buttonpayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, 230));

        jPanel2.add(panelpayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 330, 250));

        paneledit.setBackground(new java.awt.Color(0, 80, 80));
        paneledit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.black, null));
        paneledit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paneleditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paneleditMouseExited(evt);
            }
        });
        paneledit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonedit.setBackground(new java.awt.Color(255, 255, 255));
        buttonedit.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        buttonedit.setForeground(new java.awt.Color(255, 255, 255));
        buttonedit.setIcon(new javax.swing.ImageIcon("C:\\Users\\DIPU\\Desktop\\JU_Fees_Management\\src\\main\\java\\dipu\\Icons\\edit.png")); // NOI18N
        buttonedit.setText("Edit Course");
        buttonedit.setToolTipText("");
        buttonedit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonedit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttoneditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttoneditMouseExited(evt);
            }
        });
        paneledit.add(buttonedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, 230));

        jPanel2.add(paneledit, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 330, 250));

        panelview.setBackground(new java.awt.Color(0, 80, 80));
        panelview.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.black, null));
        panelview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelviewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelviewMouseExited(evt);
            }
        });
        panelview.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonview.setBackground(new java.awt.Color(255, 255, 255));
        buttonview.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        buttonview.setForeground(new java.awt.Color(255, 255, 255));
        buttonview.setIcon(new javax.swing.ImageIcon("C:\\Users\\DIPU\\Desktop\\JU_Fees_Management\\src\\main\\java\\dipu\\Icons\\text-book-opened-from-top-view.png")); // NOI18N
        buttonview.setText("View All Record");
        buttonview.setToolTipText("");
        buttonview.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonviewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonviewMouseExited(evt);
            }
        });
        panelview.add(buttonview, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, 220));

        jPanel2.add(panelview, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 330, 250));

        panellogout.setBackground(new java.awt.Color(0, 80, 80));
        panellogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.black, null));
        panellogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panellogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panellogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panellogoutMouseExited(evt);
            }
        });
        panellogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonlogout.setBackground(new java.awt.Color(255, 255, 255));
        buttonlogout.setFont(new java.awt.Font("Arial", 0, 27)); // NOI18N
        buttonlogout.setForeground(new java.awt.Color(255, 255, 255));
        buttonlogout.setIcon(new javax.swing.ImageIcon("C:\\Users\\DIPU\\Desktop\\JU_Fees_Management\\src\\main\\java\\dipu\\Icons\\logout_1.png")); // NOI18N
        buttonlogout.setText(" Logout ");
        buttonlogout.setToolTipText("");
        buttonlogout.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonlogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonlogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonlogoutMouseExited(evt);
            }
        });
        panellogout.add(buttonlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, 230));

        jPanel2.add(panellogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, 330, 250));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 960, 770));

        setSize(new java.awt.Dimension(975, 811));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void panelpaymentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelpaymentMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelpaymentMouseEntered

    private void panelpaymentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelpaymentMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panelpaymentMouseExited

    private void paneleditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneleditMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_paneleditMouseEntered

    private void paneleditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneleditMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_paneleditMouseExited

    private void panellogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panellogoutMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panellogoutMouseEntered

    private void panellogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panellogoutMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panellogoutMouseExited

    private void buttonpaymentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonpaymentMouseEntered
Color clr = new Color(0,50,50);
        panelpayment.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_buttonpaymentMouseEntered

    private void buttonpaymentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonpaymentMouseExited
Color clr = new Color(0, 100, 100);
        panelpayment.setBackground(clr);        // TODO add your handling code here:
    }//GEN-LAST:event_buttonpaymentMouseExited

    private void buttoneditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttoneditMouseEntered
        Color clr = new Color(0,50,50);
        paneledit.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_buttoneditMouseEntered

    private void buttoneditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttoneditMouseExited
         Color clr = new Color(0, 100, 100);
        paneledit.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_buttoneditMouseExited

    private void buttonlogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonlogoutMouseEntered
        Color clr = new Color(0,50,50);
        panellogout.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_buttonlogoutMouseEntered

    private void buttonlogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonlogoutMouseExited
        Color clr = new Color(0, 100, 100);
        panellogout.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_buttonlogoutMouseExited

    private void panelviewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelviewMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panelviewMouseExited

    private void panelviewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelviewMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelviewMouseEntered

    private void buttonviewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonviewMouseExited
        Color clr = new Color(0, 100, 100);
        panelview.setBackground(clr);// TODO add your handling code here:
    }//GEN-LAST:event_buttonviewMouseExited

    private void buttonviewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonviewMouseEntered
        Color clr = new Color(0,50,50);
        panelview.setBackground(clr); // TODO add your handling code here:
    }//GEN-LAST:event_buttonviewMouseEntered

    private void buttonpaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonpaymentMouseClicked
          dispose();
        Payment h=new Payment();
        h.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_buttonpaymentMouseClicked

    private void panellogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panellogoutMouseClicked
        dispose();
        Homepage h=new Homepage();
        h.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_panellogoutMouseClicked

    private void buttonlogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonlogoutMouseClicked
        dispose();
        Homepage h=new Homepage();
        h.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_buttonlogoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buttonedit;
    private javax.swing.JLabel buttonlogout;
    private javax.swing.JLabel buttonpayment;
    private javax.swing.JLabel buttonview;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel paneledit;
    private javax.swing.JPanel panellogout;
    private javax.swing.JPanel panelpayment;
    private javax.swing.JPanel panelview;
    // End of variables declaration//GEN-END:variables
}
